image: node:18

stages:
  - build
  - deploy

cache:
  paths:
    - node_modules/

variables:
  CI: "true"

before_script:
  - cd landing
  - npm install

build:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - build/

deploy:
  stage: deploy
  script:
    - apt-get update -qq && apt-get install -y lftp
    - lftp -c "
        open -u $FTP_USERNAME,$FTP_PASSWORD $FTP_HOST;
        mirror -R --delete ./build $FTP_DIRECTORY
      "
  only:
    - dev