stages:
  - build
  - deploy

build:
  stage: build
  image: node:18
  script:
    - cd landing
    - npm install
    - npm run build
  artifacts:
    paths:
      - dist/

deploy:
  stage: deploy
  image: debian:latest
  script:
    - echo "FTP_USER=$FTP_USER"
    - echo "FTP_HOST=$FTP_HOST"
    - apt-get update -qy
    - apt-get install -y lftp
    - ls -la landing/public
    - lftp -c "open -u $FTP_USER,$FTP_PASS $FTP_HOST; mirror -R ./landing/public /public_html/dev.finby.tech"
  only:
    - dev