image: node:18

stages:
  - build
  - test
  - deploy

cache:
  paths:
    - landing/node_modules/

variables:
  CI: "true"

before_script:
  - cd landing
  - npm cache clean --force
  - rm -rf node_modules/.cache
  - npm ci
  - echo "Current directory:"
  - pwd
  - echo "Listing all files and directories:"
  - ls -la
  - find . -type d -print

build:
  stage: build
  script:
    - npm run build
    - echo "Checking if build directory exists..."
    - ls -la build
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
        
  artifacts:
    paths:
      - landing/build/

test:
  stage: test
  script:
    - npm run test -- --coverage --watchAll=false
  artifacts:
    paths:
      - landing/coverage/
    expire_in: 1 week
  coverage: '/All files[^|]*\|[^|]*\s+([\d\.]+)%/'      

deploy:
  stage: deploy
  image: debian:latest
  before_script:
    - apt-get update -qy && apt-get install -y lftp
    - echo "$FTP_SERVER_CERT" > /tmp/server.crt
    - mkdir -p /etc/ssl/certs
    - cp /tmp/server.crt /etc/ssl/certs/server.crt
  script:
    - lftp -c "set ftp:ssl-force true; set ftp:ssl-protect-data true; set ssl:verify-certificate no; open -u bhvaac_0,NBuVsD7LPJkcG9BZ www200.your-server.de; mirror -R landing/build finby.tech"
  only:
    - master