image: node:18

stages:
  - build
  - deploy

cache:
  paths:
    - node_modules/

variables:
  CI: "true"

before_script:
  - cd landing
  - npm install
  - echo "Current directory:"
  - pwd
  - echo "Listing all files and directories:"
  - ls -la
  - find . -type d -print

build:
  stage: build
  script:
    - npm run build
    - echo "Checking if build directory exists..."
    - ls -la build
  artifacts:
    paths:
      - build/

deploy:
  stage: deploy
  script:
    - apt-get install -y lftp
    - lftp -c "set ftp:ssl-force true; set ftp:ssl-protect-data true; set ssl:verify-certificate no; open -u $FTP_USER,$FTP_PASS $FTP_HOST; mirror -R ./build $FTP_PATH "
  only:
    - dev