image: node:18

stages:
  - build
  - deploy

cache:
  paths:
    - node_modules/

variables:
  CI: "true"

before_script:
  - cd landing
  - npm install
  - echo "Current directory:"
  - pwd
  - echo "Listing all files and directories:"
  - ls -la
  - find . -type d -print

build:
  stage: build
  script:
    - npm run build
    - echo "Checking if build directory exists..."
    - ls -la build
  artifacts:
    paths:
      - build/

deploy:
  stage: deploy
  script:
    - apt-get update -qq && apt-get install -y lftp
    - echo "FTP_USER=bhvaac_0"
    - echo "FTP_PASS=NBuVsD7LPJkcG9BZ"
    - echo "FTP_HOST=www200.your-server.de"
    - echo "FTP_PATH=/public_html"
    - echo "Connecting to FTP server..."
    - lftp -e "debug; open -u $FTP_USERNAME,$FTP_PASSWORD $FTP_HOST; ls; bye"
    - lftp -c "set ftp:ssl-allow no; open -u $FTP_USERNAME,$FTP_PASSWORD $FTP_HOST; mirror -R --delete ./build $FTP_DIRECTORY "
  only:
    - dev