stages:
  - deploy

deploy:
  stage: deploy
  image: debian:latest
  script:
    - apt-get update -qy
    - apt-get install -y lftp
    - lftp -c "open -u $FTP_USER,$FTP_PASS $FTP_HOST; mirror -R ./landing/public /dev.finby.tech"
  only:
    - dev