stages:
  - install
  - build

install_dependencies:
  stage: install
  image: node:18
  script:
    - cd landing
    - npm install
  cache:
    paths:
      - node_modules/

build:
  stage: build
  image: node:16
  script:
    - npm run build
  artifacts:
    paths:
      - build/