stages:
  - install
  - build

# Этап установки зависимостей
install_dependencies:
  stage: install
  image: node:18
  script:
    - npm install
  cache:
    paths:
      - node_modules/

# Этап сборки
build:
  stage: build
  image: node:16
  script:
    - npm run build
  artifacts:
    paths:
      - build/