name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: landing/package-lock.json
      
      - name: Install dependencies
        run: |
          cd finby.tech/landing
          npm ci
      
      - name: Build project
        run: |
          cd finby.tech/landing
          npm run build
           echo "Build output:"
           ls -la finby.tech/landing/build || echo "Build directory does not exist!"
      
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: finby.tech/landing/build

      - name: Debug build output
        run: |
          cd finby.tech/landing
          ls -la build || echo "Build directory does not exist!"
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: landing/package-lock.json
      
      - name: Install dependencies
        run: |
          cd landing
          npm ci
      
      - name: Run tests
        run: |
          cd landing
          npm run test -- --coverage --watchAll=false
      
      - name: Upload test coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: landing/coverage

      - name: Debug build path
        run: |
             echo "Current working directory:"
             pwd
             echo "Landing directory contents:"
             ls -la landing
             echo "Build directory contents:"
             ls -la landing/build || echo "Build directory not found!"
             
  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Install lftp
        run: sudo apt-get update -qy && sudo apt-get install -y lftp
      
      - name: Deploy via FTP
        env:
          FTP_SERVER: ${{ secrets.FTP_SERVER }}
          FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        run: |
          lftp -c "
          set ftp:ssl-force true;
          set ftp:ssl-protect-data true;
          set ssl:verify-certificate no;
          open -u $FTP_USERNAME,$FTP_PASSWORD $FTP_SERVER;
          mirror --verbose --reverse --delete --continue landing/build dev.finby.tech
          "
